blog/urls.py
# -*- coding: utf-8 -*-
from blog.views import BlogList, PostDitail, CreatePost, \
    EditPost, DelPost, ApiBlogjs, ApiCreateblogjs, ApiDetailblogjs, \
    ApiEditblogjs, AllPostsReact, CreatePostReact, DetailPostReact, EditPostReact
from django.urls import path, re_path, include
app_name = 'blog'

urlpatterns = [

    re_path(r'^$', BlogList, name='blogs_list'),
    # re_path(r'^ditail/(?P<pk>[0-9]+)/$', PostDitail, name='ditail')
    path('ditail/<int:pk>/', PostDitail, name='ditail'),
    path('create/', CreatePost, name='create'),
    path('<int:pk>/edit/', EditPost, name='edit'),
    path('<int:pk>/delete/', DelPost, name='delete'),
    # js
    path('apiblogjs/', ApiBlogjs, name='apiblogjs'),
    path('apicreateblogjs/', ApiCreateblogjs, name='apicreateblogjs'),
    path('apidetailblogjs/<int:pk>', ApiDetailblogjs, name='apidetailblogjs'),
    path('apieditblogjs/<int:pk>', ApiEditblogjs, name='apieditblogjs'),
    # react
    path('allpostsreact/', AllPostsReact, name='allpostsreact'),
    path('reatepostreact/', CreatePostReact, name='reatepostreact'),
    path('detailblogreact/<int:pk>', DetailPostReact, name='detailblogreact'),
    path('editlblogreact/<int:pk>', EditPostReact, name='editlblogreact'),
    path('__debug__/', include('debug_toolbar.urls')),

    # url(r'^myac/new/$', 'myforact.views.myac_new', name='myac_new'),
    # url(r'^myac/(?P<pk>[0-9]+)/$', 'myforact.views.myac_detal', name='myac_detal'),
    # url(r'^myac/(?P<pk>[0-9]+)/edit/$', 'myforact.views.myac_edit', name='myac_edit'),
    # url(r'^myac/(?P<pk>[0-9]+)/del/$', 'myforact.views.myac_delete', name='myac_delete'),
]

blog/models.py
#-*- coding: utf-8 -*-
import datetime
#from datetime import datetime

from django.db import models
from django.utils import timezone

class Mypost(models.Model):
    class Meta:
        db_table = 'myforact_app'
        verbose_name_plural = 'Активные формы'

    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField('Заголовок', max_length=12)
    text = models.TextField('Запись', blank=False)
    # created_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateField('Дата публикации', auto_created=True, default=datetime.date.today)
    # publish_date = models.DateField(blank=True, null=True, auto_created=True)
    photo = models.ImageField(upload_to='photo_blog/%Y/%m/%d', blank=True, null=True, default='user_default_profile.jpg',)
    done = models.BooleanField(default=False)

    def publish(self):
        self.publish_date=timezone.now()
        self.save()

    def __str__(self):
        # return self.title
        return f'My post: {self.title}({"" if self.done else "not"}done)'

class Comment(models.Model):

    class Meta:
        verbose_name_plural = 'Комментарии'

    blogpost = models.ForeignKey(Mypost, related_name='comments', on_delete=models.CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __int__(self):
        return self.id


class MainPage(models.Model):

    class Meta:
        verbose_name = 'Текст на главной'
        verbose_name_plural = 'Текст на главной'

    title = models.CharField('Заголовок', max_length=120)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    done = models.BooleanField('Активный', default=False)

    def __str__(self):
        return self.title

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from blog.models import Mypost

class CreateForms(forms.ModelForm):

    title = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Название'}), max_length=24)

    class Meta:
            model = Mypost
            fields = ('title', 'text', 'publish_date', 'photo')

blog/api/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView

from blog.models import Mypost, Comment
from blog.api.serializers import PostSerializer, CommentSerializer


class PostListView(APIView):
    # parser_classes = (FormParser, MultiPartParser)

    def get(self, request):
        # выводим все посты  апи
        items = Mypost.objects.all()
        serializer = PostSerializer(items, many=True)
        return Response(serializer.data)

    def post(self, request):
        print('POST')
        print(request.data)
        # добавляем пост
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid():
            print(serializer.errors)
            serializer.save()
            print('save')
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CommentDetailView(generics.RetrieveAPIView):
    # выводим все коменты апи
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class PostListUrlView(APIView):
    # queryset = Post.objects.filter(title='first news')
    # выводим один пост по айди

    def get(self, request, pk):
        posts = Mypost.objects.filter(id=pk)

        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)

    def put(self, request, pk):
        print('put')
        print(request.POST)
        print(request.data)
        print('request.data.photo')

        photo = request.data['photo']

        print('photo')
        print(photo)
        #  photo_blog/2021/12/15/069.jpg
        snippet = get_object_or_404(Mypost, pk=pk)
        serializer = PostSerializer(snippet, data=request.data)
        print('serializer')
        print(serializer)
        if serializer.is_valid():
            print("1")
            # if request.POST['photo'] != ['undefined']:
            # print(serializer.errors)
            serializer.save()
            return Response(serializer.data)
        else:
            my_photo = Mypost.objects.filter(pk=pk).values('photo')
            # print('my_photo')
            # print(my_photo[0]['photo'])

            # if title == '' or text == '':
            #     return JsonResponse({'res': '0'})
            # else:
            Mypost.objects.filter(pk=pk).update(title=request.POST['title'], text=request.POST['text'],
                                                photo=my_photo[0]['photo'])  # , photo=request.POST['photo']
            return Response(serializer.data)
            # return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):

        print('delete')
        snippet = get_object_or_404(Mypost, pk=pk)
        # serializer = PostSerializer(snippet)
        # data = serializer.data
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

# class PostListUrlView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Mypost.objects.all()
#     serializer_class = CommentSerializer

blog/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from blog.models import Mypost, MainPage
from blog.forms import CreateForms
# Create your views here.


def index(request):
    all_posts = Mypost.objects.all()
    maintext = MainPage.objects.all()
    # print('all_posts_all')
    # print(all_posts)
    context = {'maintext': maintext}
    return render(request, 'index.html', context)


def BlogList(request):
    all_posts = Mypost.objects.all()
    # print('all_posts_all')
    # print(all_posts)
    context = {'all_posts': all_posts}
    return render(request, 'blogs_list.html', context)

def PostDitail(request, pk):
    post_ditail = Mypost.objects.all().filter(pk=pk)

    print('post_ditail')
    print(post_ditail[0])
    return render(request, 'blog_ditail.html', {'post_ditail': post_ditail[0]})

def CreatePost(request):
    if request.method == 'POST':
        form = CreateForms(request.POST, request.FILES)
        if form.is_valid():
            create_post = form.save(commit=False)
            create_post.author = request.user
            create_post.save()
            return redirect('blog:ditail', pk=create_post.pk)
    else:
        form = CreateForms

    return render(request, 'create.html', {'form': form})

def EditPost(request, pk):
    # edit_post1 = get_object_or_404(Mypost, pk=pk)

    edit_post = Mypost.objects.filter(pk=pk).get()
    if request.method == 'POST':
        form = CreateForms(request.POST, request.FILES, instance=edit_post)
        # print('form')
        # print(form)

        if form.is_valid():
            edit = form.save(commit=False)
            # edit.author = request.user
            # print('edit.author')
            # print(edit.author)
            edit.save()
            return redirect('blog:ditail', pk=edit.pk)
    else:
        form = CreateForms(instance=edit_post)

    return render(request, 'edit.html', {'form': form})

def DelPost(request, pk):
    del_post = Mypost.objects.get(pk=pk)
    if request.method == 'POST':
        form = CreateForms(request.POST, instance=del_post)
        if form.is_valid():
            del_post = form.save(commit=False)
            del_post.delete()
            return redirect('blog:blogs_list')
    else:
        form = CreateForms(instance=del_post)
    return render(request, 'delete.html', {'form': form})

# def PagePostApi(request):
#
#     if request.method == 'POST':
#         form = CreateForms(request.POST)
#         if form.is_valid():
#             create_post = form.save(commit=False)
#             create_post.author = request.user
#             create_post.save()
#             return redirect('blog:ditail', pk=create_post.pk)
#     else:
#         form = CreateForms
#     return render(request, 'index.html', {'form': form} )

def ApiBlogjs(request):
    return render(request, 'apiblogjs.html', )

def ApiCreateblogjs(request):
    return render(request, 'apicreateblogjs.html',)

def ApiDetailblogjs(request, pk):
    post_ditail = Mypost.objects.all().filter(pk=pk)
    return render(request, 'apidetailblogjs.html',{'post_ditail': post_ditail[0]})

def ApiEditblogjs(request, pk):
    post_ditail = Mypost.objects.all().filter(pk=pk)
    return render(request, 'apieditblogjs.html',{'post_ditail': post_ditail[0]})

###   ResctJS   #####
def AllPostsReact(request):
    return render(request, 'react_post/allreact.html', )

def CreatePostReact(request):
    return render(request, 'react_post/createpostreact.html',)

def DetailPostReact(request, pk):
    post_ditail = Mypost.objects.all().filter(pk=pk)
    return render(request, 'react_post/detailreact.html',{'post_ditail': post_ditail[0]})

def EditPostReact(request, pk):
    post_ditail = Mypost.objects.all().filter(pk=pk)
    return render(request, 'react_post/editpostreact.html',{'post_ditail': post_ditail[0]})

blog/templates/apiblogjs.html
{% extends "base.html" %}
{% load static %}

{% block title %}JS{% endblock title %}

{% block content %}
<div class=""></div>
    <div class="myPosts myPosts_style row row-blog-list"></div>

{% endblock content %}

{% block apiblogJS %}

    <script type="text/javascript" src="{% static "api/js/apiblogjs.js" %}"></script><!--без этого не загружается 2212-->

{% endblock apiblogJS %}

blog/templates/apidetailblogjs.html
{% extends "base.html" %}
{% load static %}

{% block title %}Detail JS{% endblock title %}
{% block content %}
    <div class=""></div>
    <div class="myPostsDetail"></div>

    {% comment %}<div class="d-flex justify-content-start">
        <div class=" m-4 p-4">
            <span> Django </span>
            <img class="main_img" src="{{ MEDIA_URL }}{{ post_ditail.photo }}" width="176" height="185">
        </div>

        <div class="d-flex flex-column m-4 p-4">
            <div>Детальное описание</div>
            <div>Номер:{{ post_ditail.pk }}</div>
            <div>Автор:  {{ post_ditail.author }}</div>
            <div>Тайтл: {{ post_ditail.title }}</div>
            <div>Текст: {{ post_ditail.text }}</div>
            <div>Дата: {{ post_ditail.publish_date }}</div>

            {% if post_ditail.publish_date %}
                <div class="date">

                    <input type="button" onclick="editeGist({{ post_ditail.pk }})"><span>редактировать </span>
                    <input type="button" onclick="deleteGist({{ post_ditail.pk }})"><span>Удалить</span>
                </div>
            {% endif %}
        </div>
    </div>{% endcomment %}

    <script>

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function editeGist (idpost){
            let pk = idpost
            location.href='/blog/apieditblogjs/' + pk

        }


    function deleteGist (idpost){
        let pk = idpost
        let csrftoken = getCookie('csrftoken');
        fetch("http://127.0.0.1:8991/api/posts/" + pk, {
            method: "delete",
            credentials: "same-origin",
            headers: {
                "X-CSRFToken": csrftoken,
            },
        }).then(function (response) {
            {#console.log('response.json()')#}
            if (response){
                location.href='/blog/apiblogjs/'
            }

        })
    }


    </script>

{% endblock content %}

{% block apiblogJS %}

    <script type="text/javascript" src="{% static "api/js/apidetailblogjs.js" %}"></script><!--без этого не загружается 2212-->

{% endblock apiblogJS %}

blog/templates/apieditblogjs.html
{% extends "base.html" %}
{% load static %}

{% block title %}edit JS{% endblock title %}
{% block content %}
    edit JS

    {#<div><a href="{% url 'blog:blogs_list' %}"><span>Главная</span></a></div>#}
    <div class=" d-flex justify-content-center">
        <form enctype="multipart/form-data" class="needs-validation" novalidate>
            <div class=" d-flex justify-content-center">
                <div class=" d-flex flex-column m-5">
                    <label for="validationCustom03" class="form-label">Название</label>
                    <input class="form-control col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2" type="text" name="publish_title" value="{{ post_ditail.title }}"  id="validationTooltip01" aria-describedby="inputGroupPrepend"  required>
                    <div class="invalid-feedback invalid-feedback-file">
                        Введите название
                    </div>
                    <label for="validationCustom02" class="form-label mt-2">Подробно</label>
                    <textarea type="text" class="form-control mb-2"  name="publish_text" id="validationTextarea" required>{{ post_ditail.text }}</textarea>
                    <div class="invalid-feedback">
                        Введите текст
                    </div>
                    <input class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12 mt-2 mb-2" type="file" name="publish_photo"><a href="{{ MEDIA_URL }}{{ post_ditail.photo }}">{{ post_ditail.photo }}</a>
                    <input class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12 mt-2 mb-2" type="button" onclick="handleFiles({{ post_ditail.pk }})" value="Сохранить запись">
                </div>
            </div>
        </form>
    </div>

    <script>

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        async function editeGist (idpost){

            //alert(idpost)
            var publish_author = 'default'
            var publish_title = document.getElementsByName('publish_title')[0].value
            var publish_text = document.getElementsByName('publish_text')[0].value
            let pk = idpost
            let csrftoken = getCookie('csrftoken');
            const formData = new FormData();
            const fileField = document.querySelector('input[type="file"]');
            console.log('photo')
            console.log(fileField.files[0])
            formData.append('author', publish_author);
            formData.append('title', publish_title);
            formData.append('text', publish_text);
            formData.append('photo', fileField.files[0]);
            console.log('formData')
            console.log(formData)
            /*fetch("http://127.0.0.1:8991/api/posts/" + pk, {
                method: "put",
                credentials: "same-origin",
                headers: {
                    "X-CSRFToken": csrftoken,
                },
                body: formData
            })*/
            try {
                const response = await fetch("http://127.0.0.1:8991/api/posts/" + pk, {
                    method: 'PUT',
                    credentials: "same-origin",
                    headers: {
                        'Content-type': 'application/json; charset=UTF-8',
                        "X-CSRFToken": csrftoken,
                    },
                    body: formData
                });
                const result = await response.json();
                console.log('Успех:', JSON.stringify(result));
                if (result.res == '0'){
                    console.log('введены не все данные')
                    console.log(result)
                }else{
                    location.href = 'http://127.0.0.1:8991/blog/apidetailblogjs/' + pk
                }
            } catch (error) {
                console.error('Ошибка:', error);
            }
            /*.then(function (response) {
                {#console.log('response.json()')#}
                if (response){
                    console.log('response')
                    console.log(response.text())
                   {#location.href = 'http://127.0.0.1:8991/blog/apidetailblogjs/' + pk#}
                }
            })*/
            {#.then(data=>console.log(data.json()))#}
            {#.then(data1=>console.log(data1))#}
        }

        // Пример стартового JavaScript для отключения отправки форм при наличии недопустимых полей
        function handleFiles(idpost) {
            'use strict'
            // Получите все формы, к которым мы хотим применить пользовательские стили проверки Bootstrap   handleFiles()
            var forms = document.querySelectorAll('.needs-validation')
            // Зацикливайтесь на них и предотвращайте отправку
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }
                        form.classList.add('was-validated')
                        console.log('idpost')
                        console.log(idpost)
                        editeGist(idpost)
                    }, false)
                })
        }


    </script>
{% endblock content %}

blog/templates/blog_ditail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{#<div><a href="{% url 'blog:blogs_list' %}"><span>Главная</span></a></div>#}
    <div class="d-flex justify-content-start">
        <div class=" m-4 p-4">
            <span> </span>
            <img class="main_img" src="{{ MEDIA_URL }}{{ post_ditail.photo }}" width="176" height="185">
        </div>

        <div class="d-flex flex-column m-4 p-4">
            <div>Детальное описание</div>
            <div>Номер:{{ post_ditail.pk }}</div>
            <div>Автор:  {{ post_ditail.author }}</div>
            <div>Тайтл: {{ post_ditail.title }}</div>
            <div>Текст: {{ post_ditail.text }}</div>
            <div>Дата: {{ post_ditail.publish_date }}</div>

            {% if post_ditail.publish_date %}
                <div class="date d-flex flex-column">
                    {% csrf_token %}
                    <a class="text-decoration-none btn border-2 border-success mb-2 mt-1" href="{% url 'blog:edit' pk=post_ditail.pk %}"><span style="color: blue">редактировать </span></a>
                    <a class="text-decoration-none btn border-2 border-danger" href="{% url 'blog:delete' pk=post_ditail.pk %}"><span>Удалить</span></a>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock content %}

blog/templates/blogs_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Django{% endblock title %}

{% block content %}
    <div class="row row-blog-list">
        {% for all_posts_s in all_posts %}
        {#    <div>Номер поста {{ all_posts_s.pk }}</div>#}
        {#    <div>{{ all_posts_s.author }}</div>#}
                <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-3 child-row">
                    <h3><a class="text-decoration-none" href="{% url 'blog:ditail' all_posts_s.pk %}">{{ all_posts_s.title }}</a></h3>
                    <div><span>Номер поста: </span>{{ all_posts_s.pk }}</div>
                    <div><span> </span><img class="main_img" src="{{ MEDIA_URL }}{{ all_posts_s.photo }}" ></div>
                    <div><span>Название: </span>{{ all_posts_s.title }}</div>
                    <div class="text-truncate"><span>Текст: </span>{{ all_posts_s.text }}</div>
                    <div><span>Публикации: </span>{{ all_posts_s.publish_date }}</div>
                </div>
        {% endfor %}
    </div>
{% endblock content %}

blog/templates/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}create Django{% endblock title %}

{% block content %}
    create

    {#<div><a href="{% url 'blog:blogs_list' %}"><span>Главная</span></a></div>#}
    <div class=" d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class=" d-flex flex-column">
        <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.label }}</div>
        <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.title }}</div>
        <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.text }}</div>
        <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.publish_date }}</div>
        <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.photo }}</div>
            <input class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2" type="submit" value="Добавить запись" />
        </div>

    </form>
    </div>



{% endblock content %}

blog/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div><a href="{% url 'blog:blogs_list' %}"><span>Главная</span></a></div>
<form method="POST">
    {% csrf_token %}
{#    <div type='hidden'{{ form.as_table }}></div>#}
    <div>{{ form.title }}</div>
    <div>{{ form.text }}</div>
    <div>{{ form.publish_date }}</div>
    <input type="submit" value="Удалить запись"/>
</form>
</body>
</html>

blog/templates/edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
edit

{#<div><a href="{% url 'blog:blogs_list' %}"><span>Главная</span></a></div>#}
    <div class=" d-flex justify-content-center">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <div class=" d-flex flex-column">
                    <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.label }}</div>
                    <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.title }}</div>
                    <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.text }}</div>
                    <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.publish_date }}</div>
                    <div class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2">{{ form.photo }}</div>
                    <input class="col-6 col-sm-5 col-md-4 col-lg-3 col-xl-12  mt-2 mb-2" type="submit" value="Редактировать запись" />
                </div>
        </form>

    </div>
{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Главная{% endblock title %}



    {% block content %}
<div class="mt-5">
        {% for maintext in maintext %}
            {%  if maintext.done == True %}
        <div class="h3 text-capitalize text-center">{{ maintext.title }}</div>
            <div>{{ maintext.text|safe }}</div>
            <div>{{ maintext.created }}</div>
            {% endif %}
        {% endfor %}
</div>
    {% endblock content %}