blog/urls.py
# -*- coding: utf-8 -*-
from blog.views import BlogList, PostDitail, CreatePost, \
    EditPost, DelPost, ApiBlogjs, ApiCreateblogjs, ApiDetailblogjs, \
    ApiEditblogjs, AllPostsReact, CreatePostReact, DetailPostReact, EditPostReact
from django.urls import path, re_path, include
app_name = 'blog'

urlpatterns = [

    re_path(r'^$', BlogList, name='blogs_list'),
    # re_path(r'^ditail/(?P<pk>[0-9]+)/$', PostDitail, name='ditail')
    path('ditail/<int:pk>/', PostDitail, name='ditail'),
    path('create/', CreatePost, name='create'),
    path('<int:pk>/edit/', EditPost, name='edit'),
    path('<int:pk>/delete/', DelPost, name='delete'),
    # js
    path('apiblogjs/', ApiBlogjs, name='apiblogjs'),
    path('apicreateblogjs/', ApiCreateblogjs, name='apicreateblogjs'),
    path('apidetailblogjs/<int:pk>', ApiDetailblogjs, name='apidetailblogjs'),
    path('apieditblogjs/<int:pk>', ApiEditblogjs, name='apieditblogjs'),
    # react
    path('allpostsreact/', AllPostsReact, name='allpostsreact'),
    path('reatepostreact/', CreatePostReact, name='reatepostreact'),
    path('detailblogreact/<int:pk>', DetailPostReact, name='detailblogreact'),
    path('editlblogreact/<int:pk>', EditPostReact, name='editlblogreact'),
    path('__debug__/', include('debug_toolbar.urls')),

    # url(r'^myac/new/$', 'myforact.views.myac_new', name='myac_new'),
    # url(r'^myac/(?P<pk>[0-9]+)/$', 'myforact.views.myac_detal', name='myac_detal'),
    # url(r'^myac/(?P<pk>[0-9]+)/edit/$', 'myforact.views.myac_edit', name='myac_edit'),
    # url(r'^myac/(?P<pk>[0-9]+)/del/$', 'myforact.views.myac_delete', name='myac_delete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
{#        <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>#}
{#        <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>#}
{#        <script src="https://unpkg.com/babel-standalone@6.17.0/babel.min.js"></script>#}
{#    <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>#}
{#    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>#}
{#    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>#}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>#}
{##}

    <link rel="stylesheet" href="{% static "blog/blog.css" %}" type="text/css">

{% block extrahead %}
{#    <script src="https://unpkg.com/react@16/umd/react.development.js"></script>#}
{#    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>#}
{#    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>#}
{% endblock %}
{#    <link rel="stylesheet" href="{% static "todo/css/style.css" %}" type="text/css">#}

    <title> {% block title %}DRF{% endblock title %}</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }

        .top-container {
            background-color: #f1f1f1;
            padding: 30px;
            text-align: center;
        }

        .header {
            padding: 10px 16px;
            background: #555;
            color: #f1f1f1;
        }

        .content {
            padding: 16px;
        }

        .sticky {
            position: fixed;
            top: 0;
            width: 100%;
        }

        .sticky + .content {
            padding-top: 102px;
        }
    </style>


</head>
<body>

<div class="top-container">
    <h1>Просто блог</h1>
    <p>Выгрузка из базы данных и создание постов DRF JS ReactJS</p>
</div>
<div class="header d-flex justify-content-center text-decoration-none" id="myHeader">
{#    <div class="d-flex justify-content-between text-decoration-none"></div>#}
{% block base_header %}
    <div class="btn btn-secondary btn-size m-4"><h3><a class="text-decoration-none" href="{% url 'index' %}"><span class="text-white">Главная</span></a></h3></div>

    <div class="btn-group btn-size m-4">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
            <h3>Django</h3>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuClickableInside">
            <li><a class="text-decoration-none dropdown-item" href="{% url 'blog:blogs_list' %}"><span class="text-black">Django</span></a></li>
            <li><a class="text-decoration-none dropdown-item" href="{% url 'blog:create' %}"><span class="text-black">Добавить пост</span></a></li>
        </ul>
    </div>

    <div class="btn-group btn-size m-4">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
            <h3>JS</h3>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuClickableInside">
            <li><a class="text-decoration-none dropdown-item" href="{% url 'blog:apiblogjs' %}"><span class="text-black">JS</span></a></li>
            <li><a  class="text-decoration-none dropdown-item" href="{% url 'blog:apicreateblogjs' %}"><span class="text-black">Добавить пост</span> </a></li>
        </ul>
    </div>

    <div class="btn-group btn-size m-4">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
            <h3>ReactJS</h3>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuClickableInside">
            <li><a class="text-decoration-none dropdown-item"  href="{% url 'blog:allpostsreact' %}"><span class="text-black">ReactJS</span></a></li>
            <li><a class="text-decoration-none dropdown-item" href="{% url 'blog:reatepostreact' %}"><span class="text-black">Добавить пост</span> </a></li>
        </ul>
</div>

            <div class="btn btn-secondary btn-size m-4"><h3><a class="text-decoration-none" href="{% url 'api_post_list' %}"><span class="text-white">API DRF</span> </a></h3></div>

</div>

{% endblock base_header %}





<div class="container">
{% block header %}
{% endblock header %}
</div>
<div class="container">
{% block content %}
{% endblock content %}
</div>

{#<div id="app">#}

</div>
<!--  JS -->

{#<script type="text/javascript" src="{% static "api/js/createpostreact.js" %}"></script>#}

{#    <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>#}
{#    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>#}
{#    <script src="https://unpkg.com/babel-standalone@6.17.0/babel.min.js"></script>#}
{#    <script type="text/javascript" src="{% static "api/js/apiblogreact.js" %}"></script>#}

{% block react %}{% endblock react %}

{% block JS_main %}
{##}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

{% endblock JS_main %}
{% block apiblogJS %}
{% endblock apiblogJS %}
<script>
// {% block apidetailblogJS %}
// {% endblock apidetailblogJS %}
</script>





<div class="container">
    {% block footer %}
        <!-- Footer -->
        <div class="footer">
            <p class="mt-3 d-block">BLOgS vs API</p>
        </div>
        <!-- Footer -->


    <script>
        // sticky header
        window.onscroll = function() {myFunction()};

        var header = document.getElementById("myHeader");
        var sticky = header.offsetTop;

        function myFunction() {
            if (window.pageYOffset > sticky) {
                header.classList.add("sticky");
            } else {
                header.classList.remove("sticky");
            }
        }


    </script>


    {% endblock footer %}
</div>
</body>
</html>